#####################################################################
# post-processing file for results generated by FastQC
#####################################################################

# assign variables
results_dir=$1

# concatenate all summary.txt files
for d in */; do cat $d/summary.txt >> summaries_all.txt ; done
 



