#####################################################################
# post-processing file for results generated by FastQC
#####################################################################

# assign variables
results_dir=$1

# concatenate all summary.txt files

 



